version: '3.1'

services:
  tech-blog-mvc-node:
    container_name: tech-blog-mvc-node
    image: node:18.16.1-alpine
    restart: always
    volumes: 
      - .:/usr/src/app
    working_dir: /usr/src/app
    ports: 
      - 4002:3000
    command: >
      /bin/sh -c "npm install
      && npm start"
    depends_on:
      - tech-blog-mvc-mysql
    
  tech-blog-mvc-mysql:
    container_name: tech-blog-mvc-mysql
    image: mysql
    restart: always
    volumes:
      - tech-blog-mvc-mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports: 
      - 3306:3306
    
  tech-blog-mvc-db-admin:
    container_name: tech-blog-mvc-db-admin
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=tech-blog-mvc-mysql
      - PMA_PORT=3306

volumes:
  tech-blog-mvc-mysql: